export const SET_REPOS_PARAMS = "SET_REPOS_PARAMS";
export const SELECT_REPOS_PAGE = "SELECT_REPOS_PAGE";
export const INVALIDATE_REPOS_PAGE = "INVALIDATE_REPOS_PAGE";

export const REPOS_REQUEST = "REPOS_REQUEST";
export const REPOS_SUCCESS = "REPOS_SUCCESS";
export const REPOS_FAILURE = "REPOS_FAILURE";
