export const SET_REPOS_QUERY = "SET_REPOS_QUERY";
export const SET_REPOS_SORT = "SET_REPOS_SORT";
export const SET_REPOS_ORDER = "SET_REPOS_ORDER";
export const SELECT_REPOS_PAGE = "SELECT_REPOS_PAGE";
export const INVALIDATE_REPOS_PAGE = "INVALIDATE_REPOS_PAGE";

export const REPOS_REQUEST = "REPOS_REQUEST";
export const REPOS_SUCCESS = "REPOS_SUCCESS";
export const REPOS_FAILURE = "REPOS_FAILURE";
